### ISSUE TITLE
The problem with how hostnames are added

### ISSUE THREAD

**Issue by edwardloveall** [gabebw/hotline-webring#58]
The way it currently works is when a link is incoming, we normalize the url to be just the hostname and store that as the URL to redirect to. This has a couple of problems:
- If the next/prev links are on a subpage, it's hard to find the links
- If multiple users from a single site want to join the webring, they can't without manual intervention on our part.

However, if we switch to using the full referrer, we have another set of problems:
- If someone has the webring links as part of their website's global template, they could trigger a new redirection to be added.

Example: http://nuthole.com and http://nuthole.com/blog/2016/05/03/jack-shirt/ 

This can be fixed by only allowing one link per hostname, but that removes the possibility of having multiple members from a single site (like tilde.town).

Another option: an application form like [cuties.online](http://cuties.online/?Join)

This is a little bit of work to build (and not as slick) but would fix both of these problems. A user would pick what url to redirect to and we wouldn't have any accidentals adds.

Putting this out there to consider options.

**Comment by gabebw** [comment]
I'm leaning towards an application form (probably a Google form that submits to both of our email addresses).

Reasons:

* no edge cases
* impossible to game
* no more accidentally adding people and asking them if they meant to do that
* humans can handle the tilde.town cases
* I don't think filling out the form will decrease participation _that_ much; people are highly motivated to join our exclusive, cool webring

**Comment by edwardloveall** [comment]
Sounds good. I'd vote for a non-google form. I think they look pretty crappy. If it's the only free option, I'll code one up.

**Comment by gabebw** [comment]
These are the options:

* Google forms (free), doesn't look good
* Formkeep ($29/month), styleable
* [Typeform](https://www.typeform.com/), ([free](https://www.typeform.com/pricing/)), looks good

Looks like Typeform is the winner.

**Comment by gabebw** [comment]
As of December 20, 2018, we store the whole original referring URL (#115) in addition to the hostname, which might (with some rare manual intervention on our part) make this issue go away.

>If the next/prev links are on a subpage, it's hard to find the links

We check each new link that's added to make sure this isn't an issue (which honestly I enjoy, since it means the webring is growing!), and now that we have the full URL we can fix it if necessary.

>If multiple users from a single site want to join the webring, they can't without manual intervention on our part.

I think the reasoning above about checking each new URL fixes this too.

>However, if we switch to using the full referrer, we have another set of problems:
>
> * If someone has the webring links as part of their website's global template, they could trigger a new redirection to be added.

I still agree with this; we don't use the full referer, but we _store_ it just in case.

@edwardloveall Are you OK with closing this issue now? If HLWR explodes in popularity, we may need to revisit, but I'd be delighted if that were the case.

**Comment by edwardloveall** [comment]
Yup, this is great. Meeting adjourned. Good work everyone.
